#!/bin/sh

#
# myYearbook.com
#
# * Contributors
#  - Dallas Gutauckis <dallas@myyearbook.com>
#

# Get device list
devices=`adb devices | grep -v "List of devices" | grep -vE "^$" | awk '{ print $1 }'`

for device in ${devices};
do
  echo "\033[0;34;34m$device\033[0m";
  adb -s $device $@;
done; 
